  0%|          | 0/50 [02:12<?, ?it/s]
Error durante el experimento: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/josei/workspace/RN/RNENV/lib64/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 41, in do_one_step
    data = pin_memory(data, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josei/workspace/RN/RNENV/lib64/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 98, in pin_memory
    clone[i] = pin_memory(item, device)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josei/workspace/RN/RNENV/lib64/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 64, in pin_memory
    return data.pin_memory(device)
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Experimento terminado para efficientnet_b5.sw_in12k__lots_aug_bn_drp
